import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const root = fileURLToPath(new URL("..", import.meta.url));
const vendorFiles = [
  "vendor/emulator/index.html",
  "vendor/emulator/data/loader.js",
  "vendor/emulator/data/emulator.min.js",
  "vendor/emulator/data/emulator.min.css",
  "vendor/emulator/data/version.json",
  "vendor/emulator/data/cores/cores.json",
  "vendor/emulator/data/cores/mgba-legacy-wasm.data",
  "vendor/emulator/data/cores/mgba-wasm.data",
  "vendor/emulator/data/cores/mgba-thread-legacy-wasm.data",
  "vendor/emulator/data/cores/mgba-thread-wasm.data"
];

const assets = Object.fromEntries(vendorFiles.map((relativePath) => [
  relativePath,
  readFileSync(resolve(root, relativePath)).toString("base64")
]));

const version = JSON.parse(readFileSync(resolve(root, "vendor/emulator/data/version.json"), "utf8")).version;
const assetDigest = createHash("sha256").update(JSON.stringify(assets)).digest("hex").slice(0, 12);
const output = `// Generated by scripts/generate-vendor.mjs. Do not edit manually.\nexport const BUNDLED_EMULATOR_ASSET_VERSION = ${JSON.stringify(`emulatorjs-${version}-${assetDigest}`)};\nexport const BUNDLED_EMULATOR_ASSETS: Record<string, string> = ${JSON.stringify(assets)};\n`;
writeFileSync(resolve(root, "src/generated-vendor.ts"), output, "utf8");
